# Generated by Django 5.2.17 on 2026-08-24 12:34

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('farmers', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Attendance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(default=django.utils.timezone.now, help_text='Date of attendance record (YYYY-MM-DD)')),
                ('check_in', models.TimeField(blank=True, help_text='Time of check-in', null=True)),
                ('check_out', models.TimeField(blank=True, help_text='Time of check-out', null=True)),
                ('total_hours', models.FloatField(blank=True, default=0.0, help_text='Computed duration in decimal hours', null=True)),
                ('location', models.CharField(blank=True, help_text='GPS coordinates or assigned field name', max_length=255, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('farmer', models.ForeignKey(help_text='Farmer associated with this attendance record', on_delete=django.db.models.deletion.CASCADE, related_name='attendances', to='farmers.farmer')),
            ],
            options={
                'verbose_name': 'Attendance',
                'verbose_name_plural': 'Attendance Records',
                'ordering': ['-date', '-check_in'],
            },
        ),
    ]
