# Generated by Django 5.2.17 on 2026-08-31 05:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='attendance',
            name='email_error',
            field=models.TextField(blank=True, help_text='Error details if email delivery failed', null=True),
        ),
        migrations.AddField(
            model_name='attendance',
            name='email_sent',
            field=models.BooleanField(default=False, help_text='Whether checkout summary email was sent to farmer and admin'),
        ),
        migrations.AddField(
            model_name='attendance',
            name='email_sent_at',
            field=models.DateTimeField(blank=True, help_text='Timestamp when checkout summary email was dispatched', null=True),
        ),
        migrations.AddField(
            model_name='attendance',
            name='work_description',
            field=models.TextField(blank=True, help_text='Work/task description completed during shift session entered at checkout', null=True),
        ),
    ]
