# Generated by Django 5.2.17 on 2026-08-24 12:34

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AnimalLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('animal_type', models.CharField(help_text='Detected animal species (e.g. lion, deer, wolf)', max_length=100)),
                ('confidence', models.FloatField(blank=True, help_text='Model confidence score between 0.0 and 1.0', null=True)),
                ('timestamp', models.DateTimeField(default=django.utils.timezone.now, help_text='Detection event timestamp')),
                ('field', models.CharField(default='Main Field', help_text='Camera field location', max_length=150)),
                ('image_path', models.CharField(help_text='Relative storage path to captured snapshot image', max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Animal Detection Log',
                'verbose_name_plural': 'Animal Detection Logs',
                'ordering': ['-timestamp'],
            },
        ),
    ]
