# Generated by Django 5.2.17 on 2026-08-26 02:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('detection', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='animallog',
            name='threat_level',
            field=models.CharField(choices=[('HIGH', 'High Threat'), ('MEDIUM', 'Medium Threat'), ('LOW', 'Low Threat')], db_index=True, default='MEDIUM', help_text='Assessed animal threat level (HIGH, MEDIUM, LOW)', max_length=10),
        ),
    ]
