# Generated by Django 5.2.17 on 2026-08-24 12:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('detection', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Alert',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('alert_type', models.CharField(help_text="Notification channel: 'Email + Buzzer', 'Email', or 'Log Only'", max_length=50)),
                ('status', models.CharField(default='Triggered', help_text="Alert dispatch status (e.g. 'Triggered', 'Sent', 'Failed')", max_length=30)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('animal_log', models.ForeignKey(blank=True, help_text='Animal detection log event associated with this alert', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='alerts', to='detection.animallog')),
            ],
            options={
                'verbose_name': 'Alert',
                'verbose_name_plural': 'Alerts',
                'ordering': ['-id'],
            },
        ),
    ]
