# Generated by Django 5.2.17 on 2026-08-26 02:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alerts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='alert',
            name='buzzer_triggered',
            field=models.BooleanField(default=False, help_text='Whether hardware audio buzzer was sounded for this alert'),
        ),
        migrations.AddField(
            model_name='alert',
            name='email_sent',
            field=models.BooleanField(default=False, help_text='Whether email notification dispatch was successfully completed'),
        ),
        migrations.AddField(
            model_name='alert',
            name='threat_level',
            field=models.CharField(choices=[('HIGH', 'High Threat'), ('MEDIUM', 'Medium Threat'), ('LOW', 'Low Threat')], db_index=True, default='HIGH', help_text='Severity tier of the triggered hazard alert (HIGH, MEDIUM, LOW)', max_length=10),
        ),
    ]
