# Generated by Django 5.2.17 on 2026-08-24 13:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AlertReceiver',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Recipient name or role title', max_length=150)),
                ('email', models.EmailField(help_text='Recipient email address', max_length=255, unique=True)),
                ('is_active', models.BooleanField(default=True, help_text='Master toggle to enable or disable alerts for this recipient')),
                ('receive_animal_alerts', models.BooleanField(default=True, help_text='Receive real-time animal hazard alerts')),
                ('receive_attendance_reports', models.BooleanField(default=False, help_text='Receive daily worker attendance summaries')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Alert Receiver',
                'verbose_name_plural': 'Alert Receivers',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='EmailSenderConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sender_name', models.CharField(default='FarmSync Alert System', help_text='Display name for outgoing emails', max_length=150)),
                ('sender_email', models.EmailField(default='alerts@example.com', help_text='Sender email address', max_length=255)),
                ('smtp_host', models.CharField(default='smtp.gmail.com', help_text='SMTP server hostname', max_length=255)),
                ('smtp_port', models.IntegerField(default=587, help_text='SMTP server port (typically 587 for TLS or 465 for SSL)')),
                ('smtp_username', models.CharField(blank=True, help_text='SMTP login username (usually same as email)', max_length=255, null=True)),
                ('smtp_password', models.CharField(blank=True, help_text='SMTP app password (write-only)', max_length=255, null=True)),
                ('use_tls', models.BooleanField(default=True, help_text='Use STARTTLS encryption')),
                ('use_ssl', models.BooleanField(default=False, help_text='Use SSL/TLS encryption')),
                ('is_active', models.BooleanField(default=True, help_text='Whether this sender configuration is actively used')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Email Sender Configuration',
                'verbose_name_plural': 'Email Sender Configurations',
            },
        ),
        migrations.CreateModel(
            name='ProjectSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('system_name', models.CharField(default='FarmSync Intelligent Monitoring', help_text='Application display title', max_length=150)),
                ('alert_cooldown_seconds', models.IntegerField(default=60, help_text='Cooldown duration in seconds between repeated animal alerts')),
                ('detection_confidence_threshold', models.FloatField(default=0.5, help_text='Minimum YOLO confidence score threshold (0.01 to 1.00)')),
                ('camera_device_index', models.IntegerField(default=0, help_text='OpenCV camera device hardware index (e.g. 0 for primary webcam)')),
                ('work_start_time', models.TimeField(default='08:00:00', help_text='Daily farm shift start time for attendance calculations')),
                ('wage_per_hour', models.FloatField(default=15.0, help_text='Standard hourly wage calculation rate')),
                ('detection_enabled', models.BooleanField(default=True, help_text='Master toggle for AI animal detection engine')),
                ('audio_buzzer_enabled', models.BooleanField(default=True, help_text='Toggle host machine audio alarm buzzer on high-threat detections')),
                ('email_alerts_enabled', models.BooleanField(default=True, help_text='Toggle automated email dispatches on medium/high threat detections')),
                ('threat_level_overrides', models.JSONField(blank=True, default=dict, help_text="Species-specific threat level mappings (e.g. {'wolf': 'high', 'deer': 'low'})")),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Project Settings',
                'verbose_name_plural': 'Project Settings',
            },
        ),
    ]
