# Generated by Django 5.2.17 on 2026-08-26 02:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('settings_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AnimalThreatRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('animal_name', models.CharField(db_index=True, help_text='Normalized lowercase animal species name (e.g. elephant, wolf, deer)', max_length=100, unique=True)),
                ('threat_level', models.CharField(choices=[('HIGH', 'High Threat'), ('MEDIUM', 'Medium Threat'), ('LOW', 'Low Threat')], default='MEDIUM', help_text='Assigned threat classification tier', max_length=10)),
                ('is_active', models.BooleanField(default=True, help_text='Whether this classification rule is currently active')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Animal Threat Rule',
                'verbose_name_plural': 'Animal Threat Rules',
                'ordering': ['animal_name'],
            },
        ),
        migrations.CreateModel(
            name='ThreatEmailTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('threat_level', models.CharField(choices=[('HIGH', 'HIGH'), ('MEDIUM', 'MEDIUM'), ('LOW', 'LOW')], help_text='Threat level this template applies to (HIGH, MEDIUM, LOW)', max_length=10, unique=True)),
                ('subject_template', models.CharField(help_text='Django template string for email subject line', max_length=255)),
                ('body_template', models.TextField(help_text='Django template string for email body content')),
                ('is_active', models.BooleanField(default=True, help_text='Whether this template is actively used for email dispatches')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Threat Email Template',
                'verbose_name_plural': 'Threat Email Templates',
                'ordering': ['threat_level'],
            },
        ),
        migrations.AddField(
            model_name='projectsettings',
            name='attach_alert_image_to_email',
            field=models.BooleanField(default=True, help_text='Attach detection snapshot JPEG to alert notification emails'),
        ),
    ]
