# Generated by Django 5.2.17 on 2026-08-24 12:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Farmer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Full name of the farm worker', max_length=150)),
                ('phone', models.CharField(help_text='Contact phone number', max_length=20)),
                ('field', models.CharField(help_text='Assigned agricultural field or work area', max_length=150)),
                ('email', models.EmailField(blank=True, help_text='Optional worker email for attendance notifications', max_length=255, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Farmer',
                'verbose_name_plural': 'Farmers',
                'ordering': ['name'],
            },
        ),
    ]
