# Generated by Django 5.2.17 on 2026-08-31 05:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('farmers', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='farmer',
            name='email',
            field=models.EmailField(default='worker@example.com', help_text='Mandatory worker email for attendance and report notifications', max_length=255, unique=True),
        ),
    ]
